name: Build APK
on: 
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    env:
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.3.13750724
      ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/27.3.13750724
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    
    - name: Install Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev build-essential portaudio19-dev python3-dev python3-pyaudio ccache ant gradle
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36
        pip install -r requirements.txt
    
    - name: Make buildozer directory
      run: mkdir -p ~/.buildozer
    
    - name: Set up Android environment
      run: |
        echo "Setting up Android NDK path..."
        ls -la /usr/local/lib/android/sdk/ndk/
        export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/27.3.13750724
        export ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.3.13750724
        echo "ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/27.3.13750724" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/27.3.13750724" >> $GITHUB_ENV
    
    - name: Build APK
      run: |
        yes | buildozer android debug || buildozer android debug
    
    - name: List bin directory
      run: |
        echo "Contents of bin directory:"
        ls -la bin/ || echo "No bin directory found"
        find . -name "*.apk" -type f || echo "No APK files found"
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: voice-recorder-apk
        path: bin/*.apk
        if-no-files-found: error